### ISSUE TITLE
Not usable with v3.5.0

### ISSUE THREAD

**Issue by opensourceXnetbox** [drygdryg/netbox-plugin-device-map#3]
Hey @drygdryg it is not possible to use the plugin with version v3.5.0. During the upgrade prozess i've got an error.

**Comment by drygdryg** [comment]
Support for NetBox v3.5 is implemented in version 0.1.3. Upgrade the plugin with:
```
pip install -U netbox-plugin-device-map
```

**Comment by betadrome** [comment]
Hey @drygdryg thanks for fixing!
